import { z } from 'zod';
import { ToolDefinition } from '../../schemas';
import { globalTaskPlanner } from '../../task_planner';
import { globalSessionManager } from '../../session';

/**
 * Task Decomposer v3 — API-Powered Deep Step Protocol Engine
 * 
 * Uses a DEDICATED Gemini 3.1 Flash Lite model (via TaskPlannerClient) to generate
 * truly intelligent, task-specific step-by-step execution plans.
 * 
 * KEY IMPROVEMENTS over v1/v2:
 * - Steps are generated by AI, not hardcoded patterns — deeply task-specific
 * - Each step has a verification condition so the agent KNOWS when it's done
 * - Writes both JSON tracker (machine-readable) and MD tracker (human-readable)
 * - Steps are granular (action-level, not phase-level) — prevents looping
 * - STRICTLY one-time per session — the ReAct loop enforces this
 * - Saves plan to SessionStateManager for cross-message persistence
 */
export const taskDecomposerTool: ToolDefinition = {
  name: 'task_decomposer',
  description: `Decompose a complex task into smaller, actionable subtasks using AI-powered deep planning (gemini-3.1-flash-lite-preview). Use this FIRST when facing any complex, multi-step request. Returns a structured execution plan with granular steps, tool assignments, and verification conditions. NEVER call this more than once per task — the plan is persistent.
  
  Examples:
  - "Build me a full website with authentication"
  - "Create a 10-page research report on climate change"
  - "Set up CI/CD pipeline for this project"
  
  Returns: Structured plan with steps, tools, verification conditions, and dependency graph.`,
  category: 'core',
  inputSchema: z.object({
    complexTask: z.string().describe('The full complex task description from the user'),
    context: z.string().optional().describe('Additional context (file list, project type, constraints)'),
    maxSubtasks: z.number().optional().default(15).describe('Maximum number of subtasks (default: 15)')
  }),
  outputSchema: z.object({
    plan: z.array(z.any()),
    totalSteps: z.number(),
    estimatedTools: z.array(z.string())
  }),
  execute: async (input: { complexTask: string, context?: string, maxSubtasks?: number }) => {
    console.log(`[Tool: task_decomposer] Decomposing via API: "${input.complexTask.substring(0, 80)}..."`);

    try {
      // === Call the dedicated Task Planner (Gemini 3.1 Flash Lite) ===
      const planResult = await globalTaskPlanner.decompose(input.complexTask, input.context);
      const steps = planResult.steps;

      // === Write DUAL tracker files for the ReAct loop to read back ===
      const fs = require('fs-extra');

      // 1. Human-readable markdown tracker
      let trackerMd = `# INVISIBLE TASK TRACKER\n\n`;
      trackerMd += `**Goal:** ${input.complexTask}\n`;
      trackerMd += `**Created:** ${new Date().toISOString()}\n`;
      trackerMd += `**Complexity:** ${planResult.estimated_complexity}\n`;
      trackerMd += `**Est. Time:** ~${planResult.estimated_time_minutes} minutes\n`;
      trackerMd += `**Status:** IN_PROGRESS\n\n---\n\n`;

      steps.forEach((step: any) => {
        trackerMd += `- [ ] **Step ${step.step}: ${step.name}**\n`;
        trackerMd += `  - Action: ${step.description}\n`;
        trackerMd += `  - Tools: ${step.tools.join(', ')}\n`;
        trackerMd += `  - Done when: ${step.done_when}\n`;
        if (step.depends_on?.length > 0) {
          trackerMd += `  - Depends on: Step ${step.depends_on.join(', Step ')}\n`;
        }
        trackerMd += `\n`;
      });

      trackerMd += `---\n\n`;
      trackerMd += `> **PROTOCOL**: After completing each step, use \`workspace_edit_file\` to change \`[ ]\` to \`[x]\` for that step. This prevents re-doing completed work.\n`;

      // 2. Machine-readable JSON tracker (the ReAct loop reads this on every iteration)
      const trackerJson = {
        goal: input.complexTask,
        createdAt: Date.now(),
        complexity: planResult.estimated_complexity,
        estimatedMinutes: planResult.estimated_time_minutes,
        status: 'in_progress',
        steps: steps.map((s: any) => ({
          id: `step_${s.step}`,
          step: s.step,
          name: s.name,
          description: s.description,
          tools: s.tools,
          done_when: s.done_when,
          depends_on: s.depends_on,
          priority: s.priority,
          status: 'pending',  // pending | in_progress | done | skipped
          completedAt: null
        }))
      };

      try {
        fs.writeFileSync('.agent_task_tracker.md', trackerMd);
        fs.writeFileSync('.agent_task_tracker.json', JSON.stringify(trackerJson, null, 2));
        console.log(`[Tool: task_decomposer] ✅ Trackers written (${steps.length} steps, complexity: ${planResult.estimated_complexity})`);
      } catch (e) {
        console.warn("[Tool: task_decomposer] Could not write tracker files, proceeding anyway.");
      }

      // 3. Persist plan to session for cross-message continuity
      try {
        globalSessionManager.setTaskPlan(
          steps.map((s: any) => ({
            name: s.name,
            status: 'pending' as const,
            description: s.description
          }))
        );
        globalSessionManager.addAction(`Decomposed task into ${steps.length} steps: ${steps.map((s: any) => s.name).join(', ')}`);
        globalSessionManager.save().catch(() => {});
      } catch { /* silent */ }

      // Collect unique tools used across all steps
      const allTools = [...new Set(steps.flatMap((s: any) => s.tools))];

      return {
        plan: steps,
        totalSteps: steps.length,
        estimatedTools: allTools,
        complexity: planResult.estimated_complexity,
        estimatedMinutes: planResult.estimated_time_minutes,
        strategy: steps.length > 6 ? 'parallel_where_possible' : 'sequential',
        trackerFiles: ['.agent_task_tracker.md', '.agent_task_tracker.json'],
        message: `Task decomposed into ${steps.length} deep steps via AI planner (${planResult.estimated_complexity} complexity, ~${planResult.estimated_time_minutes} min). Trackers written. Execute steps ONE AT A TIME in order. After each step, mark [x] in the .md tracker. Do NOT repeat any completed step. Focus on the NEXT pending step only.`
      };
    } catch (error: any) {
      console.error(`[Tool: task_decomposer] ❌ Decomposition failed: ${error.message}`);
      return { plan: [], totalSteps: 0, estimatedTools: [], error: error.message };
    }
  }
};
